import type { Metadata } from "next";

import "./globals.css";
import { cn } from "@/lib/utils";
import { montserrat, signika, spectral } from "@/lib/fonts";



export const metadata: Metadata = {
  title: "The city of flower",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-background text-foreground",spectral.className,montserrat.className,signika.className)}
      >
        {children}
      </body>
    </html>
  );
}
